# Generated by Django 2.2 on 2019-04-13 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cifrado', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='CifradoRej',
        ),
    ]
